version: '3'

services:
  digibank-api:
    image: digibank-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: digibank
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_DB: digibank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
