version: '3'

services:
  nest-api:
    image: digibank-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: dpg-cmhj3sud3nmc73cf4gt0-a
      POSTGRES_PORT: 5432
      POSTGRES_USER: digibank_postgres_user
      POSTGRES_PASSWORD: uNu5JcROzg1xerKQnEntg1nnZ6eKGdC6
      POSTGRES_DB: digibank_postgres
    depends_on:
      - database

  database:
    image: digibank_postgres
    environment:
      POSTGRES_DB: digibank_postgres
      POSTGRES_USER: digibank_postgres_user
      POSTGRES_PASSWORD: uNu5JcROzg1xerKQnEntg1nnZ6eKGdC6
