version: '3'

services:
  network-creator:
    image: alpine:latest
    command: ["sh", "-c", "docker network create digibank-network"]
    depends_on:
      - db
    networks:
      - my-network

  digibank-api:
    image: digibank-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      jwt_secret: secretjwt4565
    depends_on:
      - database
    networks:
      - my-network

networks:
  my-network:
    external: true
    name: digibank-network
