version: '3.9'
services:
  db:
    image: postgres:15.0-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testDB
    ports:
      - '5432:5432'
    volumes:
      - ./ormconfig.ts:/app/ormconfig.ts
      - db:/var/lib/postgresql/data
volumes:
  db:
